Feature/1411947 relation and association visualization
codeBeamer-Extensions-and-Addons/codebeamer-lucidspark pull request #20
Opened 2023-10-31 13:08 UTC by C2H6Ethan

[//]: # 'This is the default template for Merge Requests'

## Feature description

**As** an end-user  
**I want to** to be able to see associations & downstream-ref relations between imported items
**So that** I can have more information visible to me, facilitating planning

[//]: # 'Describe how the feature was implemented.'
[//]: # 'Describe new views, workflow actions or logic in relation to the User Story.'
[//]: # 'If the change is technical only, specify how you improved our solution.'

### Changes

| File         | Changes                     |
| ------------ | --------------------------- |
| `example.ts` | Lorem ipsum dolor sit amet. |

## Testing approach

[//]: # 'Describe how the functionality is / can be tested'
[//]: # 'If there are unit tests, describe them'

**Scenario**: Do something with my new feature  
**Given** I set all pre-conditions up  
**When** I use the feature  
**Then** something cool happens

## How do you feel about this MR?

[//]: # "OPTIONAL, Remove this section if you don't have a gif to add"

![image](https://media.giphy.com/media/xT5LMtjiu8T2xSE8k8/giphy.gif)

## Checklist

### Assignee

-   [ ] Adequate Milestone set :triangular_flag_on_post:  
-   [ ] Adequate labels set :label:  
-   [ ] Affected documentation updated :books:
    - [ ] Changelog :bookmark_tabs:
    - [ ] Wiki :blue_book:

### Reviewer

-   [ ] Testing
    -   [ ] Coverage :ok_hand:
    -   [ ] Quality :ok_hand:
    -   [ ] Evergreen :100:
-   [ ] Code Quality
    -   [ ] :zero: new lint errors :poop:  
    -   [ ] Maintainable :tools:
    -   [ ] Good patterns :third_place:

2023-11-02 07:01 UTC, urecha requested changes
Good implementation, but a few maintenance & scalability problems need to be adressed now.

2023-11-02 07:01 UTC, urecha commented on CHANGELOG.md
> +    -   Applies to the codebeamer items in the current tracker to give the user more control over the visualization
Not entirely clear / accurate. It really just applies to `outgoing` rels / assocs from items in the currently selected tracker, right? If I have incoming ones, they aren't affected / considered. Would be important to distinguish.

2023-11-02 07:01 UTC, urecha commented on editorextensions/codebeamer-custom-ui/modal/src/api/lucidGateway.ts
> +			this.unsubscribeCallback(callback);
Not really a "subscription" if it always gets cancelled the first time you receive something.  
Should be the responsibility of the subscriber to unsubscribe again.  

Any technical reason you do this?

2023-11-02 07:01 UTC, urecha commented on editorextensions/codebeamer-custom-ui/modal/src/api/lucidGateway.ts
> +			callback(data);
Isn't this quite error-prone here?  
We just call _any_ registered callback with _any_ data we get from _any_ `message` event.  

Sounds like you could suddenly `useLines#setLines` with data of cards, rather than lines?  
Not only that, but we're also not validating the payload in the slightest. It should be checked to be a valid payload.

2023-11-02 07:01 UTC, urecha commented on editorextensions/codebeamer-custom-ui/modal/src/api/lucidGateway.ts
> +
The file's content has far exceeded the implementation of the `LucidGateway` class. About time we'd split it.

2023-11-02 07:01 UTC, urecha commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +				<span className="icon icon-arrow-line-shape mr-1 pos-adjusted-down"></span>
Icon isn't `clickable` (`cursor: pointer`). Same for the `Sync` by the way.

2023-11-02 07:01 UTC, urecha commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +					: `Show Relations & Associations (${props.missingRelationsCount})`}
![image](https://github.com/codeBeamer-Extensions-and-Addons/codebeamer-lucidspark/assets/70019423/6078f37e-79d5-49e5-b292-431bbcc25b28)

The toolbar's getting quite full. Time to start minimizing text and using icons & tooltips to the fullest.

2023-11-02 07:01 UTC, urecha commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +				disabled={props.relationsCount == 0}
![assoc_rel_counter](https://github.com/codeBeamer-Extensions-and-Addons/codebeamer-lucidspark/assets/70019423/74dc4b83-4823-42df-b6d1-581219e45bca)

If I'm quick enough to click while it's still incrementing, I'll only visualize a selection. Probably not intended?

For large amounts of items, we should make this trigger only on-demand to save on resources locally as well as remotely. Meaning the analysis of how many relations there would be to load, which I think happens in `useImportedItems`: Above a certain threshhold of for example 50 imported items, don't preload the exact amount. Either do it on-demand, or just not at all, providing just a "dumb" button.

2023-11-02 07:01 UTC, urecha commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +	onRelations: () => void;
This component here is getting too complex.  
The logic to both the `Sync` and the `Assoc & Rel` buttons should be outsourced into their own components, and they should really draw data from redux rather than by passing it through the components.

2023-11-02 07:01 UTC, urecha commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +				onClick={() => props.onRelations()}
Lacks feedback, becoming ever more apparent for larger amounts of data. The button itself should display a spinner at least.

![assoc_rel_loading_feedback](https://github.com/codeBeamer-Extensions-and-Addons/codebeamer-lucidspark/assets/70019423/2ebf441d-08a8-44ee-a724-0a8133dbcdfb)

2023-11-02 11:20 UTC, C2H6Ethan commented on editorextensions/codebeamer-custom-ui/modal/src/api/lucidGateway.ts
> +			this.unsubscribeCallback(callback);
yes, these messages callbacks are intended for one time use, we don't want old callbacks laying around passing old data for example when we switch trackerIds.

2023-11-02 11:22 UTC, C2H6Ethan commented on editorextensions/codebeamer-custom-ui/modal/src/api/lucidGateway.ts
> +			callback(data);
I implemented a action string to the payload so we can check if the callback is for getting blocks or lines and then run those callbacks

2023-11-02 12:53 UTC, C2H6Ethan commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +					: `Show Relations & Associations (${props.missingRelationsCount})`}
I added DefaultOverlayTriggers to all import action buttons

2023-11-03 07:41 UTC, urecha commented on editorextensions/codebeamer-custom-ui/modal/src/api/lucidGateway.ts
> +			this.unsubscribeCallback(callback);
Fine, if it's for all of them.

2023-11-07 07:16 UTC, urecha commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +					: `Show Relations & Associations (${props.missingRelationsCount})`}
Given the buttons are already at the bottom, you shouldn't additionally have the tooltip below them. Looks weird, threatens to be clipped; Tooltips generally go opposite of the element's own placement on the screen.

2023-11-14 09:46 UTC, C2H6Ethan commented on editorextensions/codebeamer-custom-ui/modal/src/api/lucidGateway.ts
> +
split it up into multiple classes

2023-11-14 11:41 UTC, C2H6Ethan commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +					: `Show Relations & Associations (${props.missingRelationsCount})`}
removed button text for sync and relations

2023-11-14 14:59 UTC, C2H6Ethan commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +				disabled={props.relationsCount == 0}
made it just say "toggle ..." when there are more than 50 items on the board in the current tracker, it then fetches the relations on demand. If there are less than 50 it acts as before with a loading property which disables the button incase there are still a lot of relations.

2023-11-15 07:46 UTC, urecha commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +				disabled={props.relationsCount == 0}
But there's absolutely no feedback now when we toggle on 50+?  
There should at the very least also be a loading spinner, but additionally some post-creation feedback that, maybe with some toast message, tells the user what actually happened. How many lines were created / removed. Lacking that, I'm in fact not sure it even works, see GIF.

![weirdness](https://github.com/codeBeamer-Extensions-and-Addons/codebeamer-lucidspark/assets/70019423/ae13a07e-849b-4930-8e86-f5519ede2189)

Also mind the "-293" on the `Import All` button...

2023-11-15 07:50 UTC, urecha commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +					: `Show Relations & Associations (${props.missingRelationsCount})`}
Please put the numbers back in though, where you have them. They're intel that should be there at first glance, not hidden in the tooltip.  
The explanation of the symbol / button can be on-demand / lazily loaded. I consult it once and then always know. But the amounts I'm loading can change every time I open the modal, so I need to know that directly.

2023-11-15 09:57 UTC, C2H6Ethan commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +					: `Show Relations & Associations (${props.missingRelationsCount})`}
okay, also added a loading spinner to the relation count

2023-11-15 10:12 UTC, C2H6Ethan commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +				disabled={props.relationsCount == 0}
added code to the importer so the relations button will also use its modal

2023-11-15 10:12 UTC, C2H6Ethan commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +				onClick={() => props.onRelations()}
same as other issue, fixed by using importer modal

2023-11-16 06:26 UTC, urecha commented
Looking quite neat now. 
Feedback on relations creation / deletion is on the edge of being visible, but if one focuses, they'll see it. Good enough.  

I made a couple of small adjustments, mainly in the `ImportActions`, too petty for actual review comments.

> - Remove tooltip from "Import Selected" button (obsolete)
> - Rephrase most tooltips & button texts
> Minimize & generalize words
> - Remove duplicate information (count in both button & tooltip)
> - Pull spinner in relations-button up a level
> shan't spin next to the static icon
> - Set relations icon to go downards to symbolize removing
> - (Format file)

2023-11-16 09:37 UTC, C2H6Ethan commented on editorextensions/codebeamer-custom-ui/modal/src/pages/import/components/importActions/ImportActions.tsx
> +	onRelations: () => void;
outsourced these two buttons into their own components

2023-11-16 15:01 UTC, urecha approved these changes

2023-11-16 15:03 UTC, merged